### PR TITLE
Update links to standards & update translations notes

### PR DESCRIPTION
**Pull request by remibetin**
- Add link to WCAG 2.2 standard
- ARIA 1.2 instead of ARIA 1.1
- Change standards order : WCAG 2.2 > 2.1 > 2.0
- Update Translation Notes: when to link to a translated version and when to link to an original version.

### 🌐 Impact on translations:
- Recently Updated: French
- In-progress Updates: Indonesian
- Other outdated translations: Arabic, Chinese (Simplified), Czech, Korean, Russian, Spanish.

### CODE REVIEW

**Comment by remibetin** [comment]
@shawna-slh Better to list WCAG standards in reverse order? 

- WCAG 2.2
- WCAG 2.1
- WCAG 2.0

Instead of:
- WCAG 2.0
- WCAG 2.1
- WCAG 2.2

What do you think?

**Comment by remibetin** [comment]
@shawna-slh Ready to publish. See description for more context.

**Comment by shawna-slh** [comment]
@remibetin I also updated
> [[WCAG 2.1 at a Glance]]

to

> [[WCAG 2 at a Glance]]

**Comment by remibetin** [comment]
QA done: ✅

**Pull request merged**
