### PR TITLE
[ready for publication] Add ko translation

### PR DESCRIPTION
**Pull request by yonguilee**

### CODE REVIEW

**Comment by yonguilee** [comment]
@slhenry , KO translation is done and also reviewed. 
It can be published. :)

Reviewer info : Jun Ho Lee (gomjunho@gmail.com)

**Comment by yatil** [comment]
@yonguilee Can you do two things for us to finish it out? In the following block:
 
```yaml
# translators: 
# - name: "Yong Ui Lee"   # Replace @@ with translator name
#  link: "https://twitter.com/yongui9"
# contributors:
# - name: "Jun Ho Lee"
#  link: "redacted@gmail.com"
```

- [ ] Remove the `#` signs
- [ ] Remove the line with the email address (we don’t publish email addresses on the website if we can help it :-D)

Thanks!

**Comment by yonguilee** [comment]
@yatil , Please check :)

**Comment by yatil** [comment]
It is ready for review now :-)

**Comment by yatil** [comment]
@slhenry  I’ll publish it tomorrow morning my time when my brain has not turned to pudding due to the heat yet ;-)

**Comment by yatil** [comment]
@slhenry @yonguilee It is now published! https://www.w3.org/WAI/standards-guidelines/ko

And because we use the double brackets notation (`[[Link Text]](/path/to/document/)`), the videos page saw the change and removed the “in English” text from the link, as can be seen in this comparison image:

Screenshot of a comparison between the rendered HTML before the translation of this page was available, and after

**Pull request merged**
