### PR TITLE
[ ready to be published!] [fr] French translation

### PR DESCRIPTION
**Pull request by code-elegant**

### CODE REVIEW

**Comment by slhenry** [comment]
Thanks, @code-elegant code-elegant !

**Comment by yatil** [comment]
The title says “[ to be reviewed ]”, was that @slhenry’s review? Or do we get review from other translators? It would be easier to use labels or communicate the status more clearly.

Also, I was assigned to this and I don’t know if that means it is ready to publish as it says “to be reviewed”.

**Comment by yatil** [comment]
@slhenry If anything is ready to publish, you can just merge it and it will be published. No need to tag/assign me to push the button :-D

**Comment by slhenry** [comment]
> @slhenry If anything is ready to publish, you can just merge it and it will be published. No need to tag/assign me to push the button :-D

I like it to be QAed when published/site re-gened &mdash; so that's on @yatil for now. ;-)

**Comment by yatil** [comment]
@slhenry Thanks for the clarification. (I usually do spot checks when publishing anyway :-D)

**Comment by slhenry** [comment]
And I appreciate the "extra set of eyes" on it!

**Pull request merged**
