### PR TITLE
[ready to publish] es - Spanish translation

### PR DESCRIPTION
**Pull request by cmunch**
Changes proposed after the review by Jorge and Martin.

### CODE REVIEW

**Comment by cmunch** [comment]
@slhenry, @rumoroso, @espinr... could not find the option to update the other pull request with the proposed changes. I implemented the changes in my fork and created a new pull request thinking that this way the pull request would get updated… but it seems I did something wrong and created a new pull request. Sorry!

**Comment by rumoroso** [comment]
Hi Carlos (@cmunch), what I did in the pull request that I have for being reviewed was to commit and push the changes directly to the branch that is part of the pull request. It automatically updated everything and I guess the rest of people that was tracking it (reviewers and people that commented on it) were notified. Hope it helps ;)

**Comment by slhenry** [comment]
@cmunch This will work out just fine. :-)

For the future, you can select the option button at the bottom  "() Commit directly to the es-translation branch." and it will update the existing pull request.

**Comment by slhenry** [comment]
@rumoroso, @espinr Thank you very much for your continued review and collaboration. Please let us know if this is ready for publication, or if you have other input.

**Comment by slhenry** [comment]
replaced by 
then https://github.com/w3c/wai-std-gl-overview/pull/22

**Comment by rumoroso** [comment]
For me it is ok. Well done @cmunch :)

**Pull request merged**
